-- ElMellyBarber · esquema D1 (el Worker también lo crea solo la primera vez que se usa).
CREATE TABLE IF NOT EXISTS em_settings (id INTEGER PRIMARY KEY,address TEXT NOT NULL,phone TEXT NOT NULL,pin_hash TEXT NOT NULL,recovery_q TEXT NOT NULL,recovery_a_hash TEXT NOT NULL,schedule_json TEXT);
CREATE TABLE IF NOT EXISTS em_services (id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,duration INTEGER NOT NULL,online INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS em_clients (id TEXT PRIMARY KEY,name TEXT NOT NULL,whatsapp TEXT UNIQUE NOT NULL,visits INTEGER NOT NULL DEFAULT 0,cancellations INTEGER NOT NULL DEFAULT 0,late_cancellations INTEGER NOT NULL DEFAULT 0,no_shows INTEGER NOT NULL DEFAULT 0,total_spent INTEGER NOT NULL DEFAULT 0,last_visit TEXT);
CREATE TABLE IF NOT EXISTS em_appointments (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,service_id TEXT NOT NULL,service_name TEXT NOT NULL,price INTEGER NOT NULL,duration INTEGER NOT NULL,date TEXT NOT NULL,time TEXT NOT NULL,status TEXT NOT NULL,source TEXT NOT NULL DEFAULT 'online',notes TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,cancelled_at TEXT,late_cancel INTEGER NOT NULL DEFAULT 0,cancel_source TEXT,cancel_reason TEXT,no_show_at TEXT,reminded_at TEXT);
CREATE TABLE IF NOT EXISTS em_slots (date TEXT NOT NULL,time TEXT NOT NULL,owner_id TEXT NOT NULL,kind TEXT NOT NULL,PRIMARY KEY(date,time));
CREATE TABLE IF NOT EXISTS em_blocks (id TEXT PRIMARY KEY,date TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,whole_day INTEGER NOT NULL DEFAULT 0,reason TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS em_notifications (id TEXT PRIMARY KEY,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,seen INTEGER NOT NULL DEFAULT 0,pushed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS em_client_notifications (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,seen INTEGER NOT NULL DEFAULT 0,pushed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS em_sessions (token_hash TEXT PRIMARY KEY,expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS em_auth_attempts (kind TEXT NOT NULL,ip TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS em_daily_summaries (date TEXT PRIMARY KEY,turns INTEGER NOT NULL DEFAULT 0,revenue INTEGER NOT NULL DEFAULT 0,cancelled INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS em_push_subs (id TEXT PRIMARY KEY,role TEXT NOT NULL,client_id TEXT NOT NULL DEFAULT '',endpoint TEXT NOT NULL,p256dh TEXT NOT NULL,auth TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(endpoint,role,client_id));
CREATE INDEX IF NOT EXISTS idx_client_notifications ON em_client_notifications(client_id,seen,created_at);
CREATE INDEX IF NOT EXISTS idx_auth_attempts ON em_auth_attempts(kind,ip,created_at);
CREATE INDEX IF NOT EXISTS idx_appt_date_time ON em_appointments(date,time);
CREATE INDEX IF NOT EXISTS idx_appt_client ON em_appointments(client_id,date);
CREATE INDEX IF NOT EXISTS idx_blocks_date ON em_blocks(date);
CREATE INDEX IF NOT EXISTS idx_notifications_seen ON em_notifications(seen,created_at);
CREATE INDEX IF NOT EXISTS idx_push_role ON em_push_subs(role,client_id);
